services:
  frag-tracker-app:
    container_name: frag-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: frag-tracker-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  ngrok:
    container_name: frag-tracker-ngrok
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - '4040:4040'
    depends_on:
      - frag-tracker-app
    command: ngrok http --host-header="rewrite" --domain=witty-primarily-chow.ngrok-free.app frag-tracker-app:3000

volumes:
  postgres_data:
