services:
  frag-tracker-app:
    container_name: frag-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on: []

  ngrok:
    container_name: frag-tracker-ngrok
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - '4040:4040'
    depends_on:
      - frag-tracker-app
    command: ngrok http --host-header="rewrite" --domain=witty-primarily-chow.ngrok-free.app frag-tracker-app:3000
