import 'dotenv/config';
const config = {
  DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
  DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID,

  FACEIT_CLIENT_ID: process.env.FACEIT_CLIENT_ID,
  FACEIT_CLIENT_SECRET: process.env.FACEIT_CLIENT_SECRET,
  FACEIT_REDIRECT_URI: process.env.FACEIT_REDIRECT_URI,
};

export default config;
